# Generated by Django 6.0.2 on 2026-02-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreport',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdfs/'),
        ),
    ]
