# Generated by Django 6.0.2 on 2026-02-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clinicalreport_report_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='triage_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='triage_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
